sudo: false
language: erlang
otp_release:
  - 19.3.6.1
  - 18.3
before_install:
  - ./ci before_install "${TRAVIS_BUILD_DIR:?}"
install:
  - ./ci install "${TRAVIS_BUILD_DIR:?}"
before_script:
  - ./ci before_script "${TRAVIS_BUILD_DIR:?}"
script:
  - ./ci script "${TRAVIS_BUILD_DIR:?}"
after_success:
  - ./ci after_success "${TRAVIS_BUILD_DIR:?}"
cache:
  directories:
    - .plt
